### PR TITLE
Wrong file end of line encoding and utf8 fix

### PR DESCRIPTION
**Pull request by tim77**

### CODE REVIEW

**Comment by selmf** [comment]
Thanks for the pull request . We already fixed the line endings in the develop branch by setting default gitattributes, so there is no need to manually correct this, it will be gone when we merge the branch. 

Utf8 encoding is a different story though. We likely still have a good amount of those errors from the time when @luisangelsm wrote the comments and changelog in spanish. If you want to help getting rid of these we certainly wouldn't say no ;)

**Comment by selmf** [comment]
Thanks for the pull request . We already fixed the line endings in the develop branch by setting default gitattributes, so there is no need to manually correct this, it will be gone when we merge the branch. 

Utf8 encoding is a different story though. We likely still have a good amount of those errors from the time when @luisangelsm wrote the comments and changelog in spanish. If you want to help getting rid of these we certainly wouldn't say no ;)

**Comment by tim77** [comment]
Ah, great. `YACReader` will be in official repos soon BTW (i hope). 😊

**Comment by selmf** [comment]
Ah, great! Which distribution?

**Comment by tim77** [comment]
Apologize, even forgot to mention this. 😄 In Fedora repos.

**Pull request closed without merging**
