### PR TITLE
compileOSX.sh: add version to app

### PR DESCRIPTION
**Pull request by vitorgalvao**
Followup to https://github.com/YACReader/yacreader/issues/31#issuecomment-866274780. Untested in your setup, but it should work if I’m understanding it correctly.

Fixes https://github.com/YACReader/yacreader/issues/31.

### CODE REVIEW

**Comment by luisangelsm** [comment]
Thanks for the PR, the version and build number are now in the info.plist file, but "Get Info" doesn't show them

image

**Comment by vitorgalvao** [comment]
> the version and build number are now in the info.plist file, but "Get Info" doesn't show them

Should be fixed by the commit I just pushed, removing [the obsolete CFBundleGetInfoString](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html). As [explained by @core-code](https://github.com/YACReader/yacreader/issues/31#issuecomment-546636492):

> importantly removing the 'CFBundleGetInfoString' entry. this one has been deprecated for more than 10 years, and will actually prevent display of the version number in the Finder, even if you do add it.

**Comment by vitorgalvao** [comment]
I see one of the checks is failing, but it’s on Windows so I’m assuming it’s unrelated to this PR or was a glitch.

**Comment by vitorgalvao** [comment]
All checks passing now.

**Comment by luisangelsm** [comment]
Yeah, everything is working now, thanks for PR!!

**Pull request merged**
