### PR TITLE
Add Italian translations

### PR DESCRIPTION
**Pull request by giallorosso84**
Please, in next version, add Italian translation. Thank you

### CODE REVIEW

**Comment by giallorosso84** [comment]
> 
> 
> Please, in next version, add Italian translation. Thank you

On this forum, https://www.yacreader.com/forum/translators/1106-italian-translation, last thread, i found Italian translation, can you add it?

**Comment by selmf** [comment]
Sorry, but in the current form I am not even going to bother to look at this mess. If this is supposed to be a pull request and there is somewhere an Italian translation hidden among the commits, please change the destination branch to **develop**.

If this is supposed to be a feature request, please delete this pull request and open an issue. As none of the current team members speak Italian we probably won't be able to provide a translation, though.

I will be keeping this PR open for a few days to allow you to fix it.

**Comment by vedgy** [comment]
This pull request is obviously bogus: 
> giallorosso84 wants to merge 90 commits into master from develop

These are both *YACReader/yacreader* repository branches. Apparently @giallorosso84 asks the maintainers to follow his forum link and integrate the Italian translation attached there.

**Comment by selmf** [comment]
@vedgy yeah I figured as much, but sometimes you have to give people the opportunity to rectify their mistakes. @giallorosso84 is likely not a programmer and probably not fluent in english. Which is ok.
I don't know why the italian translations (and a chinese one) did not get added but I'm working to fix this right now.

**Comment by luisangelsm** [comment]
Yeah, closing this one.

**Pull request closed without merging**
