### PR TITLE
Added missing German translations and fixed errors

### PR DESCRIPTION
**Pull request by CandidDeer**
I'm a native German speaker, so I fixed errors in the German translations that were already present in the file and added all missing translations. I'd be delighted if you could count this PR as my contribution to HAcktoberfest. 💖

### CODE REVIEW

**Comment by luisangelsm** [comment]
thanks!

**Comment by luisangelsm** [comment]
Hey, @selmf just pinged me about the translation missing the YACReaderLibrary app, so if you are interested in update it please go ahead.

If you are looking for other non-coding tasks, maybe you can document or help other with the translation process.

Thanks again for getting involved in the project, it is really appreciated.

**Comment by luisangelsm** [comment]
That's the one, yes. Thank you!

**Comment by selmf** [comment]
@CandidDeer exactly. Feel free to open a separate PR for it

As @luisangelsm wrote, we could also use a tutorial which explains the translation process. Nothing fancy, just something to get people started and point them at the right resources. It could be a section of the README or a separate file.

**Comment by CandidDeer** [comment]
@selmf Yes, I've started work on the translation and hope to finish today. Will open a fresh PR then.
As for the tutorial, I basically just use my own language skills and one translation service for single words I get stuck on. Should I write that into the README? The link to that translation website, I mean? There aren't any other resources for me, really. 😅

**Comment by CandidDeer** [comment]
I've finished my translation work on the requested file (PR #338). 👾 Let me know how you decide about that Readme and happy coding! 🎇

**Pull request merged**
